### ISSUE TITLE
Score update stuck at 12 and not updating

### ISSUE THREAD

**Issue by carolinemusyoka** [Ashish-Kenjale/DodgeCorona#12]
I was working on issue #4 and I noticed that when Installed the app. The initial HI score is always 12 and when I advanced in the game, the score wasn't updated. Here is a screenshot.
![Screenshot_20200708-110352](https://user-images.githubusercontent.com/44951692/87027621-19efb480-c1e6-11ea-8452-d856920326ea.png)

**Comment by Ashish-Kenjale** [comment]
Hi Caroline!

The score is updated only when a virus pair leaves the screen.

So even if you dodge a virus pair, you would get that score only once that virus pair leaves the screen.

I designed it that way as the player is free to move around the whole screen.
